### PR TITLE
[SWA-64] Rearrange header

### PR DESCRIPTION
**Pull request by 0xVenky**
## Fixes: SWA-64

# Description

Update the header. Move bridge near Swap.
Add DCA to header

image

image

# How to test the changes

Check if DCA is seen and accessible

### CODE REVIEW

**Comment by NelsonGaldeman** [comment]
nit: Just one little comment regarding commit messages: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

tested it and works

**Comment by berteotti** [comment]
> nit: Just one little comment regarding commit messages: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
> 
> tested it and works

Agree. @0xVenky  you can edit the commit or squash it with a new commit message. I suggest the first one so we can approve :)

**Comment by wixzi** [comment]
You can use vs code interactive rebase to `develop` branch and do a reword and fix the commit message.
`git rebase -i develop`

https://dev.to/colbygarland/using-vs-code-to-git-rebase-1lc
https://www.youtube.com/watch?v=3o_01F04bZ4

or 
https://www.youtube.com/watch?v=4YjKY0u9Z6I

**Review by Diogomartf — APPROVED** [review]
Looks good to me 😎👌

**Review by wixzi — APPROVED** [review]

**Pull request merged**
