### PR TITLE
[SWA-67][FEAT] - Add native $USDC on Arbitrum

### PR DESCRIPTION
**Pull request by ElRodrigote**
## Fixes: [SWA-67](https://linear.app/swaprdev/issue/SWA-67/update-usdc-token-in-arbitrum)

# Description

* Add $USDC native token in Arbitrum

image

# How to test the changes

1) Pull this branch
2) Run the project locally
3) Go to Swapr landing page
4) Connect your wallet
5) $USDC and $USDC.e tokens should be among the common tokens suggested for swaps on Arbitrum One

### CODE REVIEW

**Review by berteotti — COMMENTED** [review]
Looks good to me. Will approve when pointing to the right SDK.

**Comment by 0xVenky** [comment]
Should we nashe a new sdk release for this? :o

**Comment by ElRodrigote** [comment]
> Should we make a new sdk release for this? :O

For the old $USDC to $USDC.e renaming, yes
For the new $USDC native token, no.

But if we don't rename the old one and we add the native one, we will end up having 2 $USDC tokens in the UI for Arbitrum

**Review by NelsonGaldeman — APPROVED** [review]
LGTM!

**Pull request merged**
